Citizen.CreateThread(function()
	for i=1, #Config.Logouts, 1 do
		local logoutspot = Config.Logouts[i]
		local blip = AddBlipForCoord(logoutspot)
		SetBlipSprite(blip, 480)
		SetBlipDisplay(blip, 4)
		SetBlipScale(blip, 0.8)
		SetBlipColour(blip, 4)
		SetBlipAsShortRange(blip, true)
		BeginTextCommandSetBlipName("STRING")
		AddTextComponentString("Train Station")
		EndTextCommandSetBlipName(blip)
	end
end)

Citizen.CreateThread(function()
	for i=1, #Config.beanmachine, 1 do
		local logoutspot = Config.beanmachine[i]
		local blip = AddBlipForCoord(logoutspot)
		SetBlipSprite(blip, 304)
		SetBlipDisplay(blip, 4)
		SetBlipScale(blip, 0.8)
		SetBlipColour(blip, 14)
		SetBlipAsShortRange(blip, true)
		BeginTextCommandSetBlipName("STRING")
		AddTextComponentString("Bean Machine")
		EndTextCommandSetBlipName(blip)
	end

end)

Citizen.CreateThread(function()
	for i=1, #Config.news, 1 do
		local wnews = Config.news[i]
		local blip = AddBlipForCoord(wnews)
		SetBlipSprite(blip, 205)
		SetBlipDisplay(blip, 4)
		SetBlipScale(blip, 0.6)
		SetBlipColour(blip, 4)
		SetBlipAsShortRange(blip, true)
		BeginTextCommandSetBlipName("STRING")
		AddTextComponentString("Weazel News")
		EndTextCommandSetBlipName(blip)
	end
end)

Citizen.CreateThread(function()
	local blip = AddBlipForCoord(3035.74,-304.79,13.81)
	SetBlipSprite(blip, 455)
	SetBlipDisplay(blip, 4)
	SetBlipScale(blip, 0.8)
	SetBlipColour(blip, 4)
	SetBlipAsShortRange(blip, true)
	BeginTextCommandSetBlipName("STRING")
	AddTextComponentString("Sunken Ship")
	EndTextCommandSetBlipName(blip)
end)

Citizen.CreateThread(function()
	local blip = AddBlipForCoord(4.35,-1604.83,29.31)
	SetBlipSprite(blip, 436)
	SetBlipDisplay(blip, 4)
	SetBlipScale(blip, 0.8)
	SetBlipColour(blip, 5)
	SetBlipAsShortRange(blip, true)
	BeginTextCommandSetBlipName("STRING")
	AddTextComponentString("Taco Farmer")
	EndTextCommandSetBlipName(blip)
end)

Citizen.CreateThread(function()
	local blip = AddBlipForCoord(234.07,-415.76,47.95)
	SetBlipSprite(blip, 498)
	SetBlipDisplay(blip, 4)
	SetBlipScale(blip, 0.8)
	SetBlipColour(blip, 4)
	SetBlipAsShortRange(blip, true)
	BeginTextCommandSetBlipName("STRING")
	AddTextComponentString("Court House")
	EndTextCommandSetBlipName(blip)
end)

Citizen.CreateThread(function()
	local blip = AddBlipForCoord(1853.14,3686.2,34.27)
	SetBlipSprite(blip, 60)
	SetBlipDisplay(blip, 4)
	SetBlipScale(blip, 0.8)
	SetBlipColour(blip, 28)
	SetBlipAsShortRange(blip, true)
	BeginTextCommandSetBlipName("STRING")
	AddTextComponentString("BCSO")
	EndTextCommandSetBlipName(blip)
end)